package tech.espero.gruber.fullstackchallenge.exceptions

class UserAlreadyExistsException: Exception()
